
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Chemistry'
tagline:          'from http://cnx.org/contents/85abf193-2bd2-4908-8563-90b8a7ac8df6@9.165 (CC-BY)'
url:              https://github.com/philschatz/chemistry-book
origin:           http://cnx.org/contents/85abf193-2bd2-4908-8563-90b8a7ac8df6@9.165

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          9.165

bookviewer:       http://philschatz.com/book-viewer

